// The Pawn — Hollow Chess mascot rig. Flat 2D, thick outline, big eyes.
// Eyes, brows, mouth and arms are separate parts so he can act.
//
//   const P = WCPAWN.make();  el.appendChild(P.svg);
//   P.set('smug');            // neutral | hype | smug | shocked | dead | think
//   P.mouthOpen(0..1);        // manual jaw
//   WCPAWN.idle(P);           // breathing + blinks (returns stop fn)
//   await WCPAWN.speak(P, words);        // words: [{t0,t1}] seconds from now
//   await WCPAWN.speakEnvelope(P, env);  // env: {fps, v:[0..1,...]} from a real recording
//
// Voice lines are looked up by WCPAWN.lineKey(text) → shorts/vo/pawn-<key>.{mp3,json}
// (generated by harness/pawn-vo.py). The same key function lives in that script.
(function (global) {
  'use strict';
  const NS = 'http://www.w3.org/2000/svg';
  const INK = '#14161b', IVORY = '#e9e3d6', GOLD = '#e7c14a', VOID = '#0b0c10';
  const SW = 9;

  function el(tag, attrs, parent) {
    const n = document.createElementNS(NS, tag);
    for (const k in attrs) n.setAttribute(k, attrs[k]);
    if (parent) parent.appendChild(n);
    return n;
  }
  // a limb = ink under-stroke + ivory over-stroke, so it reads on a dark background
  function limb(d, parent, w) {
    w = w || 16;
    el('path', { d, fill: 'none', stroke: INK, 'stroke-width': w + SW * 2 }, parent);
    el('path', { d, fill: 'none', stroke: IVORY, 'stroke-width': w }, parent);
  }

  const EXPR = {
    neutral: { browL: 'M132 108 Q162 96 192 108', browR: 'M208 108 Q238 96 268 108', mouth: 'M176 226 Q200 246 224 226', lid: 0, ry: 40, pupilDy: 0 },
    hype:    { browL: 'M128 88 Q160 74 194 92',   browR: 'M206 92 Q240 74 272 88',  mouth: 'M168 222 Q200 262 232 222 Z', lid: 0, ry: 46, pupilDy: -4, fillMouth: true },
    smug:    { browL: 'M134 118 Q164 108 192 114', browR: 'M206 100 Q238 84 268 96', mouth: 'M176 228 Q206 244 230 220', lid: 14, ry: 40, pupilDy: 2 },
    shocked: { browL: 'M128 82 Q162 70 194 86',   browR: 'M206 86 Q238 70 272 82',  mouth: 'M188 218 Q200 210 212 218 Q222 236 200 254 Q178 236 188 218 Z', lid: 0, ry: 50, pupilDy: -2, fillMouth: true, smallPupil: true },
    dead:    { browL: 'M132 112 Q162 118 192 120', browR: 'M208 120 Q238 118 268 112', mouth: 'M180 236 L 222 236', lid: 26, ry: 40, pupilDy: 4 },
    think:   { browL: 'M132 104 Q162 100 192 112', browR: 'M208 100 Q240 86 268 98', mouth: 'M180 232 Q200 226 222 234', lid: 6, ry: 40, pupilDy: -8, pupilDx: 8 },
  };

  function make(opts) {
    opts = opts || {};
    const svg = el('svg', { viewBox: '0 0 400 520' });
    const root = el('g', { class: 'pawn-root' }, svg);
    el('ellipse', { cx: 200, cy: 500, rx: 118, ry: 14, fill: 'rgba(0,0,0,.35)', stroke: 'none' }, root);
    const body = el('g', { stroke: INK, 'stroke-width': SW, 'stroke-linejoin': 'round', 'stroke-linecap': 'round', fill: IVORY }, root);

    const armL = el('g', {}, body);
    limb('M150 345 C 120 365, 95 385, 80 415', armL);
    el('circle', { cx: 78, cy: 420, r: 17 }, armL);

    el('rect', { x: 96, y: 452, width: 208, height: 46, rx: 20 }, body);
    el('path', { d: 'M150 300 C 142 372, 120 428, 118 458 L 282 458 C 280 428, 258 372, 250 300 Z' }, body);
    el('rect', { x: 126, y: 280, width: 148, height: 36, rx: 18 }, body);
    el('circle', { cx: 200, cy: 168, r: 112 }, body);

    const armR = el('g', {}, body);
    limb('M250 345 C 280 360, 305 375, 322 405', armR);
    const tile = el('g', { transform: 'translate(300 372) rotate(-12)' }, armR);
    el('rect', { x: -44, y: -44, width: 88, height: 88, rx: 10, fill: INK, stroke: GOLD, 'stroke-width': 7 }, tile);
    el('rect', { x: -24, y: -24, width: 48, height: 48, rx: 5, fill: VOID, stroke: 'none' }, tile);
    el('rect', { x: -14, y: -14, width: 28, height: 28, rx: 3, fill: 'none', stroke: GOLD, 'stroke-width': 3, opacity: .55 }, tile);
    el('circle', { cx: 326, cy: 410, r: 17 }, armR);
    if (opts.tile === false) tile.setAttribute('opacity', 0);

    const face = el('g', { stroke: 'none' }, root);
    const eyes = {};
    for (const side of ['L', 'R']) {
      const cx = side === 'L' ? 162 : 238;
      const g = el('g', {}, face);
      const white = el('ellipse', { cx, cy: 165, rx: 30, ry: 40, fill: '#fff', stroke: INK, 'stroke-width': 7 }, g);
      const pupil = el('circle', { cx: cx + 5, cy: 172, r: 12, fill: INK }, g);
      const glint = el('circle', { cx: cx + 10, cy: 164, r: 4, fill: '#fff' }, g);
      const lid = el('rect', { x: cx - 36, y: 165 - 44, width: 72, height: 0, fill: IVORY, stroke: 'none' }, g);
      const lidLine = el('line', { x1: cx - 30, y1: 121, x2: cx + 30, y2: 121, stroke: INK, 'stroke-width': 7, 'stroke-linecap': 'round', opacity: 0 }, g);
      eyes[side] = { white, pupil, glint, lid, lidLine, cx };
    }
    const browL = el('path', { d: EXPR.neutral.browL, fill: 'none', stroke: INK, 'stroke-width': 9, 'stroke-linecap': 'round' }, face);
    const browR = el('path', { d: EXPR.neutral.browR, fill: 'none', stroke: INK, 'stroke-width': 9, 'stroke-linecap': 'round' }, face);
    const mouth = el('path', { d: EXPR.neutral.mouth, fill: 'none', stroke: INK, 'stroke-width': 8, 'stroke-linecap': 'round', 'stroke-linejoin': 'round' }, face);

    let cur = 'neutral', look = [0, 0], jaw = 0, blinkAmt = 0;
    function applyEyes() {
      const e = EXPR[cur];
      for (const s of ['L', 'R']) {
        const y = eyes[s];
        y.white.setAttribute('ry', e.ry);
        y.pupil.setAttribute('cx', y.cx + 5 + (e.pupilDx || 0) + look[0]);
        y.pupil.setAttribute('cy', 172 + e.pupilDy + look[1]);
        y.pupil.setAttribute('r', e.smallPupil ? 8 : 12);
        y.glint.setAttribute('cx', y.cx + 10 + (e.pupilDx || 0) + look[0]);
        y.glint.setAttribute('cy', 164 + e.pupilDy + look[1]);
        const top = 165 - e.ry - 4;
        const h = Math.max(e.lid, blinkAmt * (e.ry * 2 + 8));
        y.lid.setAttribute('y', top); y.lid.setAttribute('height', h);
        y.lidLine.setAttribute('y1', top + h); y.lidLine.setAttribute('y2', top + h);
        y.lidLine.setAttribute('opacity', h > 0 ? 1 : 0);
      }
    }
    function applyMouth() {
      const e = EXPR[cur];
      if (jaw <= 0.02) { mouth.setAttribute('d', e.mouth); mouth.setAttribute('fill', e.fillMouth ? INK : 'none'); return; }
      const h = 10 + 34 * jaw, w = 22 + 6 * jaw;
      mouth.setAttribute('d', `M${200 - w} 226 Q200 ${226 + h} ${200 + w} 226 Z`);
      mouth.setAttribute('fill', INK);
    }
    const rig = {
      svg, root, tile,
      set(name) { cur = EXPR[name] ? name : 'neutral'; browL.setAttribute('d', EXPR[cur].browL); browR.setAttribute('d', EXPR[cur].browR); applyEyes(); applyMouth(); },
      get expr() { return cur; },
      mouthOpen(a) { jaw = Math.max(0, Math.min(1, a || 0)); applyMouth(); },
      blink(t) { blinkAmt = Math.max(0, Math.min(1, t || 0)); applyEyes(); },
      look(dx, dy) { look = [dx || 0, dy || 0]; applyEyes(); },
      arm(which, deg) { const g = which === 'L' ? armL : armR; g.setAttribute('transform', `rotate(${deg || 0} ${which === 'L' ? 150 : 250} 345)`); },
      showTile(on) { tile.setAttribute('opacity', on ? 1 : 0); },
      // whole-body transform: bob/squash/pop
      pose(dy, sx, sy) { root.setAttribute('transform', `translate(200 520) scale(${sx || 1}, ${sy || 1}) translate(-200 -520) translate(0 ${dy || 0})`); },
    };
    rig.set('neutral');
    return rig;
  }

  // ---- animation helpers ----------------------------------------------------
  // Breathing bob + random blinks + gentle arm sway. Returns a stop() function.
  function idle(rig, opts) {
    opts = opts || {};
    const t0 = performance.now();
    let nextBlink = 1.2, blinkAt = -1, alive = true, gesture = null;
    const rnd = (a, b) => a + Math.random() * (b - a);
    function frame() {
      if (!alive) return;
      const t = (performance.now() - t0) / 1000;
      const bob = Math.sin(t * 2.4) * (opts.bob != null ? opts.bob : 8);
      const sq = 1 + Math.sin(t * 2.4) * .012;
      let pop = 1;
      if (opts.popIn && t < .45) pop = 1 + Math.sin((t / .45) * Math.PI) * .18;
      rig.pose(bob, pop * sq, pop / sq);
      if (blinkAt < 0 && t > nextBlink) { blinkAt = t; nextBlink = t + rnd(1.8, 3.6); }
      if (blinkAt >= 0) { const k = (t - blinkAt) / .16; rig.blink(k < 1 ? Math.sin(k * Math.PI) : 0); if (k >= 1) blinkAt = -1; }
      if (!gesture) { rig.arm('L', Math.sin(t * 2.4 + 1) * 4); rig.arm('R', Math.sin(t * 2.4) * 3); }
      requestAnimationFrame(frame);
    }
    requestAnimationFrame(frame);
    return {
      stop() { alive = false; },
      // hold an arm pose for a while (e.g. point up on a beat)
      gesture(armR, armL, ms) { gesture = true; rig.arm('R', armR || 0); rig.arm('L', armL || 0); setTimeout(() => { gesture = null; }, ms || 800); },
    };
  }

  // Word-timed lip flap: words = [{t0, t1}] in seconds relative to call time.
  function speak(rig, words, opts) {
    opts = opts || {};
    return new Promise((done) => {
      const t0 = performance.now();
      const end = words.length ? words[words.length - 1].t1 : 0;
      function frame() {
        const a = (performance.now() - t0) / 1000;
        const cur = words.find((w) => a >= w.t0 && a < w.t1);
        if (cur) {
          const len = Math.max(.08, cur.t1 - cur.t0);
          const syll = Math.max(1, Math.round(len / .14));
          const ph = (a - cur.t0) / len;
          rig.mouthOpen(.3 + .7 * Math.abs(Math.sin(ph * Math.PI * syll)));
        } else rig.mouthOpen(0);
        if (a < end + .05) requestAnimationFrame(frame); else { rig.mouthOpen(0); done(); }
      }
      requestAnimationFrame(frame);
    });
  }

  // Amplitude-driven lip flap for a real recording: env = { fps, v: [0..1...] }
  // (harness/voice-envelope.py makes one from any mp3/wav).
  function speakEnvelope(rig, env) {
    return new Promise((done) => {
      const t0 = performance.now(), n = env.v.length;
      function frame() {
        const a = (performance.now() - t0) / 1000;
        const i = Math.floor(a * env.fps);
        if (i >= n) { rig.mouthOpen(0); done(); return; }
        const v = env.v[i];
        rig.mouthOpen(v < .08 ? 0 : Math.min(1, .25 + v * .9));
        requestAnimationFrame(frame);
      }
      requestAnimationFrame(frame);
    });
  }

  // Deterministic short key for a voice line (djb2, hex). Mirrored in pawn-vo.py.
  function lineKey(text) {
    let h = 5381;
    for (let i = 0; i < text.length; i++) h = ((h * 33) ^ text.charCodeAt(i)) >>> 0;
    return h.toString(16).padStart(8, '0');
  }

  global.WCPAWN = { make, idle, speak, speakEnvelope, lineKey, EXPR };
})(typeof window !== 'undefined' ? window : globalThis);
